services:
  api_ventas:
    image: ignvalladares/isy1101-api-ventas:latest
    container_name: api_ventas
    restart: unless-stopped
    environment:
      DB_ENDPOINT: 10.0.0.149
      DB_PORT: 3306
      DB_NAME: ventas_db
      DB_USERNAME: innovatech_user
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://10.0.0.149:3306/ventas_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    ports:
      - "8080:8080"

  api_despachos:
    image: ignvalladares/isy1101-api-despachos:latest
    container_name: api_despachos
    restart: unless-stopped
    environment:
      DB_ENDPOINT: 10.0.0.149
      DB_PORT: 3306
      DB_NAME: despachos_db
      DB_USERNAME: innovatech_user
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://10.0.0.149:3306/despachos_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    ports:
      - "8081:8081"
