#!/bin/bash
set -e

VENTAS_DB="${VENTAS_DB_NAME:-ventas_db}"
DESPACHOS_DB="${DESPACHOS_DB_NAME:-despachos_db}"

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE DATABASE IF NOT EXISTS \`${VENTAS_DB}\`;
CREATE DATABASE IF NOT EXISTS \`${DESPACHOS_DB}\`;
CREATE USER IF NOT EXISTS '${DB_USERNAME}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${VENTAS_DB}\`.* TO '${DB_USERNAME}'@'%';
GRANT ALL PRIVILEGES ON \`${DESPACHOS_DB}\`.* TO '${DB_USERNAME}'@'%';
FLUSH PRIVILEGES;
EOSQL
